services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3002:8000"
    volumes:
      - ./src/API/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./Uploads:/app/Uploads:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17.4-alpine3.21
    environment:
        - POSTGRES_DB=project-prod
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "127.0.0.1:3003:5432"
    volumes:
        - db:/var/lib/postgresql/data:rw
    restart: always

volumes:
  db:
